PREFIX rso: <https://www.blinded-for-review/rso#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?dimension WHERE {
    rso:Indicator94_E1-7-53-b
               rso:measuresDimension ?d .
    ?d a rso:ESGDimension ;
               rdfs:label ?dimension .
}
