PREFIX rso: <https://www.blinded-for-review/rso#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT * WHERE {
    rso:Indicator94_E1-7-53-b
               rdfs:label ?rdfLabel ;
               skos:prefLabel ?skosLabel .
}